[tool.black]
line-length = 88
exclude = '''
/(
    \.venv
  | venv
  | build
  | dist
  | __pycache__
  | \.pytest_cache
)/
'''

[project]
name = "calculator-cli"
version = "0.1.0"
description = "A modular CLI calculator"
authors = [
    { name = "Akhil Singh" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = []

[project.scripts]
calculator = "app.cli:main"

[tool.setuptools.packages.find]
where = ["src"]